// Code generated by goderive DO NOT EDIT.

package network

// deriveMaxSize returns the maximum value from the input list and the default value, if the list is empty.
func deriveMaxSize(list []int, def int) int {
	if len(list) == 0 {
		return def
	}
	m := list[0]
	list = list[1:]
	for i, v := range list {
		if v > m {
			m = list[i]
		}
	}
	return m
}
