// Code generated by github.com/alanctgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     syslogmessage.avsc
 *     fullmessage.avsc
 */

package avro

import (
	"github.com/alanctgardner/gogen-avro/container"
	"io"
)

type FullMessage struct {
	ClientAddr string
	SourceType string
	SourcePath string
	SourcePort int32
	Uid        string
	Fields     *SyslogMessage
}

func DeserializeFullMessage(r io.Reader) (*FullMessage, error) {
	return readFullMessage(r)
}

func NewFullMessageWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &FullMessage{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func NewFullMessage() *FullMessage {
	v := &FullMessage{
		Fields: NewSyslogMessage(),
	}

	return v
}

func (r *FullMessage) Schema() string {
	return "{\"fields\":[{\"name\":\"ClientAddr\",\"type\":\"string\"},{\"name\":\"SourceType\",\"type\":\"string\"},{\"name\":\"SourcePath\",\"type\":\"string\"},{\"name\":\"SourcePort\",\"type\":\"int\"},{\"name\":\"Uid\",\"type\":\"string\"},{\"name\":\"Fields\",\"type\":{\"fields\":[{\"name\":\"Facility\",\"type\":\"string\"},{\"name\":\"Severity\",\"type\":\"string\"},{\"name\":\"TimeReported\",\"type\":\"string\"},{\"name\":\"TimeGenerated\",\"type\":\"string\"},{\"name\":\"Hostname\",\"type\":\"string\"},{\"name\":\"Appname\",\"type\":\"string\"},{\"name\":\"Procid\",\"type\":\"string\"},{\"name\":\"Msgid\",\"type\":\"string\"},{\"name\":\"Properties\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"map\",\"values\":\"string\"}}}],\"name\":\"SyslogMessage\",\"namespace\":\"skewer\",\"type\":\"record\"}}],\"name\":\"FullMessage\",\"namespace\":\"skewer\",\"type\":\"record\"}"
}

func (r *FullMessage) Serialize(w io.Writer) error {
	return writeFullMessage(r, w)
}
