// Code generated by github.com/alanctgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     syslogmessage.avsc
 *     fullmessage.avsc
 */

package avro

import (
	"fmt"
	"io"
	"math"
)

type ByteWriter interface {
	Grow(int)
	WriteByte(byte) error
}

type StringWriter interface {
	WriteString(string) (int, error)
}

func encodeInt(w io.Writer, byteCount int, encoded uint64) error {
	var err error
	var bb []byte
	bw, ok := w.(ByteWriter)
	// To avoid reallocations, grow capacity to the largest possible size
	// for this integer
	if ok {
		bw.Grow(byteCount)
	} else {
		bb = make([]byte, 0, byteCount)
	}

	if encoded == 0 {
		if bw != nil {
			err = bw.WriteByte(0)
			if err != nil {
				return err
			}
		} else {
			bb = append(bb, byte(0))
		}
	} else {
		for encoded > 0 {
			b := byte(encoded & 127)
			encoded = encoded >> 7
			if !(encoded == 0) {
				b |= 128
			}
			if bw != nil {
				err = bw.WriteByte(b)
				if err != nil {
					return err
				}
			} else {
				bb = append(bb, b)
			}
		}
	}
	if bw == nil {
		_, err := w.Write(bb)
		return err
	}
	return nil

}

func readFullMessage(r io.Reader) (*FullMessage, error) {
	var str = &FullMessage{}
	var err error
	str.ClientAddr, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.SourceType, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.SourcePath, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.SourcePort, err = readInt(r)
	if err != nil {
		return nil, err
	}
	str.Uid, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Fields, err = readSyslogMessage(r)
	if err != nil {
		return nil, err
	}

	return str, nil
}

func readInt(r io.Reader) (int32, error) {
	var v int
	buf := make([]byte, 1)
	for shift := uint(0); ; shift += 7 {
		if _, err := io.ReadFull(r, buf); err != nil {
			return 0, err
		}
		b := buf[0]
		v |= int(b&127) << shift
		if b&128 == 0 {
			break
		}
	}
	datum := (int32(v>>1) ^ -int32(v&1))
	return datum, nil
}

func readLong(r io.Reader) (int64, error) {
	var v uint64
	buf := make([]byte, 1)
	for shift := uint(0); ; shift += 7 {
		if _, err := io.ReadFull(r, buf); err != nil {
			return 0, err
		}
		b := buf[0]
		v |= uint64(b&127) << shift
		if b&128 == 0 {
			break
		}
	}
	datum := (int64(v>>1) ^ -int64(v&1))
	return datum, nil
}

func readMapMapString(r io.Reader) (map[string]map[string]string, error) {
	m := make(map[string]map[string]string)
	for {
		blkSize, err := readLong(r)
		if err != nil {
			return nil, err
		}
		if blkSize == 0 {
			break
		}
		if blkSize < 0 {
			blkSize = -blkSize
			_, err := readLong(r)
			if err != nil {
				return nil, err
			}
		}
		for i := int64(0); i < blkSize; i++ {
			key, err := readString(r)
			if err != nil {
				return nil, err
			}
			val, err := readMapString(r)
			if err != nil {
				return nil, err
			}
			m[key] = val
		}
	}
	return m, nil
}

func readMapString(r io.Reader) (map[string]string, error) {
	m := make(map[string]string)
	for {
		blkSize, err := readLong(r)
		if err != nil {
			return nil, err
		}
		if blkSize == 0 {
			break
		}
		if blkSize < 0 {
			blkSize = -blkSize
			_, err := readLong(r)
			if err != nil {
				return nil, err
			}
		}
		for i := int64(0); i < blkSize; i++ {
			key, err := readString(r)
			if err != nil {
				return nil, err
			}
			val, err := readString(r)
			if err != nil {
				return nil, err
			}
			m[key] = val
		}
	}
	return m, nil
}

func readString(r io.Reader) (string, error) {
	len, err := readLong(r)
	if err != nil {
		return "", err
	}

	// makeslice can fail depending on available memory.
	// We arbitrarily limit string size to sane default (~2.2GB).
	if len < 0 || len > math.MaxInt32 {
		return "", fmt.Errorf("string length out of range: %d", len)
	}

	bb := make([]byte, len)
	_, err = io.ReadFull(r, bb)
	if err != nil {
		return "", err
	}
	return string(bb), nil
}

func readSyslogMessage(r io.Reader) (*SyslogMessage, error) {
	var str = &SyslogMessage{}
	var err error
	str.Facility, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Severity, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.TimeReported, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.TimeGenerated, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Hostname, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Appname, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Procid, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Msgid, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Properties, err = readMapMapString(r)
	if err != nil {
		return nil, err
	}

	return str, nil
}

func writeFullMessage(r *FullMessage, w io.Writer) error {
	var err error
	err = writeString(r.ClientAddr, w)
	if err != nil {
		return err
	}
	err = writeString(r.SourceType, w)
	if err != nil {
		return err
	}
	err = writeString(r.SourcePath, w)
	if err != nil {
		return err
	}
	err = writeInt(r.SourcePort, w)
	if err != nil {
		return err
	}
	err = writeString(r.Uid, w)
	if err != nil {
		return err
	}
	err = writeSyslogMessage(r.Fields, w)
	if err != nil {
		return err
	}

	return nil
}

func writeInt(r int32, w io.Writer) error {
	downShift := uint32(31)
	encoded := uint64((uint32(r) << 1) ^ uint32(r>>downShift))
	const maxByteSize = 5
	return encodeInt(w, maxByteSize, encoded)
}

func writeLong(r int64, w io.Writer) error {
	downShift := uint64(63)
	encoded := uint64((r << 1) ^ (r >> downShift))
	const maxByteSize = 10
	return encodeInt(w, maxByteSize, encoded)
}

func writeMapMapString(r map[string]map[string]string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = writeString(k, w)
		if err != nil {
			return err
		}
		err = writeMapString(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeMapString(r map[string]string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = writeString(k, w)
		if err != nil {
			return err
		}
		err = writeString(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeString(r string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil {
		return err
	}
	if sw, ok := w.(StringWriter); ok {
		_, err = sw.WriteString(r)
	} else {
		_, err = w.Write([]byte(r))
	}
	return err
}

func writeSyslogMessage(r *SyslogMessage, w io.Writer) error {
	var err error
	err = writeString(r.Facility, w)
	if err != nil {
		return err
	}
	err = writeString(r.Severity, w)
	if err != nil {
		return err
	}
	err = writeString(r.TimeReported, w)
	if err != nil {
		return err
	}
	err = writeString(r.TimeGenerated, w)
	if err != nil {
		return err
	}
	err = writeString(r.Hostname, w)
	if err != nil {
		return err
	}
	err = writeString(r.Appname, w)
	if err != nil {
		return err
	}
	err = writeString(r.Procid, w)
	if err != nil {
		return err
	}
	err = writeString(r.Msgid, w)
	if err != nil {
		return err
	}
	err = writeMapMapString(r.Properties, w)
	if err != nil {
		return err
	}

	return nil
}
