// Code generated by github.com/alanctgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     syslogmessage.avsc
 *     fullmessage.avsc
 */

package avro

import (
	"github.com/alanctgardner/gogen-avro/container"
	"io"
)

type SyslogMessage struct {
	Facility      string
	Severity      string
	TimeReported  string
	TimeGenerated string
	Hostname      string
	Appname       string
	Procid        string
	Msgid         string
	Properties    map[string]map[string]string
}

func DeserializeSyslogMessage(r io.Reader) (*SyslogMessage, error) {
	return readSyslogMessage(r)
}

func NewSyslogMessageWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &SyslogMessage{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func NewSyslogMessage() *SyslogMessage {
	v := &SyslogMessage{
		Properties: make(map[string]map[string]string),
	}

	return v
}

func (r *SyslogMessage) Schema() string {
	return "{\"fields\":[{\"name\":\"Facility\",\"type\":\"string\"},{\"name\":\"Severity\",\"type\":\"string\"},{\"name\":\"TimeReported\",\"type\":\"string\"},{\"name\":\"TimeGenerated\",\"type\":\"string\"},{\"name\":\"Hostname\",\"type\":\"string\"},{\"name\":\"Appname\",\"type\":\"string\"},{\"name\":\"Procid\",\"type\":\"string\"},{\"name\":\"Msgid\",\"type\":\"string\"},{\"name\":\"Properties\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"map\",\"values\":\"string\"}}}],\"name\":\"SyslogMessage\",\"namespace\":\"skewer\",\"type\":\"record\"}"
}

func (r *SyslogMessage) Serialize(w io.Writer) error {
	return writeSyslogMessage(r, w)
}
