// Code generated by goderive DO NOT EDIT.

package auditlogs

import (
	model "github.com/stephane-martin/skewer/model"
)

// deriveFmapResults returns an output channel where the items are the result of the input function being applied to the items on the input channel.
func deriveFmapResults(f func(*AuditMessageGroup) *model.AuditMessageGroup, in <-chan *AuditMessageGroup) <-chan *model.AuditMessageGroup {
	out := make(chan *model.AuditMessageGroup, cap(in))
	go func() {
		for a := range in {
			b := f(a)
			out <- b
		}
		close(out)
	}()
	return out
}
