// Code generated by goderive DO NOT EDIT.

package metrics

import (
	prometheus "github.com/prometheus/client_golang/prometheus"
)

// deriveFilterGatherers returns a list of all items in the list that matches the predicate.
func deriveFilterGatherers(predicate func(prometheus.Gatherer) bool, list []prometheus.Gatherer) []prometheus.Gatherer {
	out := make([]prometheus.Gatherer, 0, len(list))
	for i, elem := range list {
		if predicate(elem) {
			out = append(out, list[i])
		}
	}
	return out
}
